# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coding club 
email: codinclub-discussions@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
    the internet home of the coding club of the school of technology
    of Assam don bosco university. The club is run by the students and 
    a faculty advisor. we coduct talks at member meetups and ocassionally
    host workshops for the club members.
baseurl: ""
url: "http://codingclubdbcet.github.io" # the base hostname & protocol for your site
github_username: codingclubadbu 

# Build settings
markdown: kramdown

# Permalink
permalink: /:day/:month/:year/:title/ 

# collectons
collections:
    workshops:
        output: true
        permalink: /workshops/:path/
    projects:
        output: true
        permalink: /projects/:path/
    meetups:
        output: true
        permalink: /meetups/:path/
